### ISSUE TITLE
Stale NFS file handle

### ISSUE THREAD

**Issue by joshbenner** [blinkreaction/boot2docker-vagrant#1]
Sometimes the application will stop working, and when I attempt `fig up`, it fails with the error "stale NFS file handle"

**Comment by lmakarov** [comment]
This may be resolved with #2 (upgrade to a new vagrant box with docker 1.5.0).
Please test and report back

**Comment by joshbenner** [comment]
New box with docker 1.5.0 seems to be working better so far.
