### ISSUE TITLE
How change the default IP

### ISSUE THREAD

**Issue by yograterol** [blinkreaction/boot2docker-vagrant#18]
AT the office the network is 192.168.10.*, and the VB IP is the same range, how I can change the default IP?

**Comment by lmakarov** [comment]
@yograterol the default IP and subnet is currently hardcoded in the base image.

You will have to alter the Vagrant file to override that:
1. Add `config.vm.network "private_network", ip: "<192.168.xx.10>", id: "default-network"` below [this line](https://github.com/blinkreaction/boot2docker-vagrant/blob/master/Vagrantfile#L100)
2. Update the IP on [this line](https://github.com/blinkreaction/boot2docker-vagrant/blob/master/Vagrantfile#L141) to `192.168.xx.1`
3. `vagrant reload`

**Comment by yograterol** [comment]
@lmakarov excellent!! :) We need add that line in the Vagrantfile, my team love this tool.
