### ISSUE TITLE
client and server don't have same version (client : 1.19, server: 1.18)

### ISSUE THREAD

**Issue by davenuman** [blinkreaction/boot2docker-vagrant#20]
After running the setup.sh we're seeing this error regarding client-server version mismatch:

```
» docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)
```

So I assume we either need to downgrade the docker client, or upgrade the vagrant box docker server.

**Comment by lmakarov** [comment]
I was waiting for Docker 1.7.1 to be released and fix the issues in the humongous 1.7.0 release :D

Short-term - downgrade the client version to 1.6.x to match the server version.
Long-term - there will be a boot2docker-vagrant box with docker v1.7.0, but the update is not trivial this time - https://github.com/dduportal/boot2docker-vagrant-box/issues/23

**Comment by davenuman** [comment]
thanks @lmakarov for this info. We'll try the workaround for now.

**Comment by davenuman** [comment]
resolved, thanks
