### ISSUE TITLE
NFS mount fails with "Client credential too weak" error

### ISSUE THREAD

**Issue by lmakarov** [blinkreaction/boot2docker-vagrant#21]
NFS mount fails with `mount: RPC: Authentication error; why = Client credential too weak` on Mac.

**Comment by lmakarov** [comment]
Possible solution: 

Add the following to `/etc/nfs.conf`: 

```
nfs.server.mount.require_resv_port = 0
```

Then restarting the nfs daemon with: 

```
nfsd restart
```

Credits to: https://gist.github.com/sirkkalap/40261ed82386ad8a6409#comment-1433482

**Comment by keelahnkhan** [comment]
I got this issue too. If I just did a `vagrant reload` it goes away the second time.
