### ISSUE TITLE
machine dies and reports "aborted" state in VirtualBox

### ISSUE THREAD

**Issue by thnkloud9** [blinkreaction/boot2docker-vagrant#23]
vagrant up reports:

ringing machine 'boot2docker' up with 'virtualbox' provider...
==> boot2docker: Importing base box 'blinkreaction/boot2docker'...
==> boot2docker: Matching MAC address for NAT networking...
==> boot2docker: Setting the name of the VM: Sites_boot2docker
==> boot2docker: Clearing any previously set network interfaces...
==> boot2docker: Preparing network interfaces based on configuration...
    boot2docker: Adapter 1: nat
    boot2docker: Adapter 2: hostonly
==> boot2docker: Forwarding ports...
    boot2docker: 2375 => 2375 (adapter 1)
    boot2docker: 2376 => 2376 (adapter 1)
    boot2docker: 22 => 2222 (adapter 1)
==> boot2docker: Running 'pre-boot' VM customizations...
==> boot2docker: Booting VM...
==> boot2docker: Waiting for machine to boot. This may take a few minutes...
    boot2docker: SSH address: 127.0.0.1:2222
    boot2docker: SSH username: docker
    boot2docker: SSH auth method: private key
    boot2docker: Warning: Remote connection disconnect. Retrying...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'aborted' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

If I debug the virtual machine with the virtualbox console it seems to start without any major errors, but right at the last shell prompt it always exits into "aborted" state.  Subsequent vagrant up commands result in the same behavior.  I have also tried removing all dependencies and starting from scratch, as well as previous boot2docker image version (tried 1.5.0, 1.6.0 and 1.7.0).

OSX 10.10.2
virtualbox-4.3.28
Vagrant 1.7.2

with a fresh install of all components (using presetup and setup scripts from this repo), and no changes to the Vagrantfile or vagrant.yml

**Comment by lmakarov** [comment]
Hi @thnkloud9, you will have to debug this:

**Enable VirtualBox GUI**
Open `vagrant.yml` and set `v.gui: true`, then `vagrant reload`
This will bring up the VM console. Look for clues there.

**Debug option in vagrant**
Do `vagrant up --debug` all look though the log for possible clues.

**Comment by lmakarov** [comment]
ping @thnkloud9

**Comment by thnkloud9** [comment]
Hey, sorry, I never got this running.  I ended up using a modified version of boot2docker based on http://blog.blackfire.io/how-we-use-docker.html

but I suspect the issue I was having was possibly this: https://github.com/boot2docker/boot2docker/issues/824#issuecomment-113904164
