### ISSUE TITLE
'docker ps' from the host

### ISSUE THREAD

**Issue by zakariaboualaid** [blinkreaction/boot2docker-vagrant#26]
I wasn't able to run 'docker ps' or use any docker-compose command from my Mac, I need to vagrant ssh to do that.. any help ?

This is where I setup boot2docker-vagrant :

-- <== here (vagrant.yml, Vagrantfile)
-- code_base
-------- docker-compose.yml

**Comment by achekulaev** [comment]
Can you provide an output of 'docker ps' and 'docker-compose ps' Zakaria?

**Comment by lmakarov** [comment]
@ZakariaBoualaid do you still have issues with this?

**Comment by lmakarov** [comment]
Closing for the lack of feedback.
