### ISSUE TITLE
Permission Denied while mounting NFS shared folders

### ISSUE THREAD

**Issue by brolag** [blinkreaction/boot2docker-vagrant#27]
Hi, 

I'm getting this output when trying to set a boot2docker-vagrant instance. Can you please recommend what can I do in this case?

https://gist.github.com/anonymous/780f7fc28b44d7e393f8

Thanks, 

Alfredo.

**Comment by lmakarov** [comment]
Hi @Brolag,

Please post here the output from `cat /etc/exports` and `showmount -e`

**Comment by brolag** [comment]
Hi @lmakarov, 

Thanks for your quick answer, here is the output:

```
MacBook-Pro-de-Alfredo:gn2 alfredo$  cat /etc/exports
/Users/alfredo -alldirs -mapall=alfredo -network 192.168.59.0 -mask 255.255.255.0
# VAGRANT-BEGIN: 501 e3bca53b-d940-4d58-a2c3-cee8f47f289a
"/Users/alfredo/workspace/gn2" 192.168.10.10 -alldirs -mapall=501:20
# VAGRANT-END: 501 e3bca53b-d940-4d58-a2c3-cee8f47f289a
```

---

```
MacBook-Pro-de-Alfredo:gn2 alfredo$ showmount -e
Exports list on localhost:
/Users/alfredo                      192.168.59.0
```

**Comment by lmakarov** [comment]
@Brolag 
1. Remove `/Users/alfredo -alldirs -mapall=alfredo -network 192.168.59.0 -mask 255.255.255.0` from your `/etc/exports`
2. `sudo nfsd restart`
3. `vagrant reload`

Where did you get that record from? It overlaps/conflicts with the one set by Vagrant.
By the IP address (192.168.59.0) I can guess you were trying to set NFS mounts up manually with the stock boot2docker? :)

**Comment by brolag** [comment]
@lmakarov, done, but still getting the permission denied error. https://gist.github.com/Brolag/c535312c56285eb554c2

cat exports 

"/Users/alfredo/workspace/gn2" 192.168.10.10 -alldirs -mapall=501:20

showmount -e

Exports list on localhost:
/Users/alfredo/workspace/gn2        192.168.10.10

And yes, I tried it manually as part of a workaround I found to try to solve the issue.

**Comment by lmakarov** [comment]
@Brolag It is pretty unlikely, that the box IP would be different, but can you please check that it is indeed `192.168.10.10`?

```
vagrant ssh -c 'ifconfig | grep 192.168.10.10'
```

Also try the following (one at a time, `vagrant reload` in-between attempts):
- disable the firewall on your Mac
- change 'tcp' to 'udp' in the following [line](https://github.com/blinkreaction/boot2docker-vagrant/blob/master/Vagrantfile#L115)

**Comment by brolag** [comment]
@lmakarov,

This is the output of the first command:
MacBook-Pro-de-Alfredo:gn2 alfredo$ vagrant ssh -c 'ifconfig | grep 192.168.10.10'
Connection to 127.0.0.1 closed.

This is my routing table
https://gist.github.com/Brolag/74eb51584e592177cb18

The other steps didn't work.

**Comment by lmakarov** [comment]
@Brolag looks like the box IP address is wrong (not 192.168.10.10).
Please do a full `vagrant ssh -c 'ifconfig'`.

There should be something similar to this

```
eth1      Link encap:Ethernet  HWaddr 08:00:27:E0:D0:F2
          inet addr:192.168.10.10  Bcast:192.168.10.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fee0:d0f2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:145604 errors:0 dropped:0 overruns:0 frame:0
          TX packets:76548 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:46527209 (44.3 MiB)  TX bytes:13787799 (13.1 MiB)
```

Have you modified the Vagrantfile?

**Comment by brolag** [comment]
@lmakarov I haven´t modified it.

```
MacBook-Pro-de-Alfredo:gn2 alfredo$ vagrant ssh -c "ifconfig"
docker0   Link encap:Ethernet  HWaddr 7A:DE:10:4A:13:F0  
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::78de:10ff:fe4a:13f0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:648 (648.0 B)

eth0      Link encap:Ethernet  HWaddr 08:00:27:28:0F:77  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe28:f77/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:401 errors:0 dropped:0 overruns:0 frame:0
          TX packets:289 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:45973 (44.8 KiB)  TX bytes:38334 (37.4 KiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:CD:18:E0  
          inet addr:192.168.56.101  Bcast:192.168.56.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fecd:18e0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1524 (1.4 KiB)  TX bytes:1427 (1.3 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:80 errors:0 dropped:0 overruns:0 frame:0
          TX packets:80 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:5760 (5.6 KiB)  TX bytes:5760 (5.6 KiB)
```

**Comment by lmakarov** [comment]
For whatever reason the box is using the stock boot2docker IP range (192.168.56.x) ...
Open VirtualBox Preferences => Network => Host-only Networks and remove all adapters - http://take.ms/ITjc4. Next do a `vagrant reload`.

**Comment by brolag** [comment]
@lmakarov awesome! mounting is working fine now! Thanks a lot!

**Comment by lmakarov** [comment]
@Brolag I'm glad this works for you now :)
