### ISSUE TITLE
OSX doesn't read ~/.bashrc by default

### ISSUE THREAD

**Issue by keelahnkhan** [blinkreaction/boot2docker-vagrant#29]
I'm setting up a new user on my OSX box to use this and since it was so new, there wasn't a `~/.bashrc` or `~/.bash_profile` setup yet. OSX only reads `~/.bash_profile` when creating a new tab, which CAN then have the following in it to load the `~/.bashrc`, but  `~/.bash_profile` doesn't exist by default either.

```
# Load ~/.bashrc as well
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi
```

I'd recommend throwing an error if `~/.bashrc` doesn't already exist, and then maybe creating `~./bash_profile` and adding this line if it doesn't ? 

without it, you get this error since docker still doesn't know where to look..

```
Get http:///var/run/docker.sock/v1.19/containers/json: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```

**Comment by achekulaev** [comment]
Thanks. We've noticed this problem too. In the development branch we've already changed it to use .bash_profile. There's still work in progress on dev branch. When it's done it will be merged into master
https://github.com/blinkreaction/boot2docker-vagrant/blob/develop/setup.sh

**Comment by lmakarov** [comment]
Fixed in https://github.com/blinkreaction/boot2docker-vagrant/commit/c307923601f4b6a4dc59bcd81d630483845e5a40 and included in the most recent releases.
