### ISSUE TITLE
Errors during installation phase

### ISSUE THREAD

**Issue by mkorostoff** [blinkreaction/boot2docker-vagrant#3]
This is a report back on my first attempts to install this using the one-liner provided, e.g.

```
curl https://raw.githubusercontent.com/blinkreaction/boot2docker-vagrant/master/setup.sh | bash
```

I am running Mac OSX 10.8.5, Homebrew 0.9.5, git 2.3.0, bash 3.2
## Error 1:

This error presented immediately upon first executing the script:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/brew-cask
/usr/local/bin is not writable.

You can try again using:
  brew link brew-cask
```
## Solution:

I ran `sudo brew link brew-cask` which worked
## Error 2:

```
Error: Unknown command: cask
```
## Solution:

N/A, this is a symptom of the previous error
## Error 3:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local

Error
Could not symlink etc/bash_completion.d/docker
/usr/local/etc/bash_completion.d is not writable.

You can try again using:
  brew link docker
```
## Solution:

I ran `sudo brew link docker` and `chmod 777 /usr/local/etc/bash_completion.d` which worked
## Error 4:

```
bash: line 14: vagrant: command not found
bash: line 21: docker: command not found
```

Solution (sort of):
After running completing solutions 1-3, I attempted to rerun the script.  Which returned Error 5 (see bellow)
## Error 5:

```
brew-cask: could not find Ruby 2.0 or greater.  Try 'brew install ruby'.
```
## Solution:

This is a confusing one, because I definitely have ruby (osX native version) but maybe this script needs ruby installed via brew. I ran `sudo brew install ruby` and ruby was installed successfully.
## Error 6:

I again reran the script, and again it failed with the following output:

```
==> Symlinking Binary 'VBoxHeadless' to '/usr/local/bin/VBoxHeadless'
==> ln: /usr/local/bin/VBoxHeadless: Permission denied
Error: Command failed to execute!

==> Failed command:
["/bin/ln", "-hfs", "--", "#<Pathname:/Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless>", "#<Pathname:/usr/local/bin/VBoxHeadless>"]

==> Output of failed command:
```
## Solution:

At this this point it seemed rather clear that permissions were the problem here.  So I tried an alternate version of the one-liner supplied at the beginning of this bug report, e.g.

```
curl https://raw.githubusercontent.com/blinkreaction/boot2docker-vagrant/master/setup.sh | sudo bash
```

At this point, the script appeared to execute without error.
## Error 7:

I then gave the following commands:

```
mkdir ~/Sites/docking
cp ~/Vagrantfile ~/Sites/docking/Vagrantfile
cd ~/Sites/docking
vagrant up
```

And received the following error:

```
Vagrant failed to initialize at a very early stage:

The home directory you specified is not accessible. The home
directory that Vagrant uses must be both readable and writable.

You specified: /Users/matt/.vagrant.d
```
## Solution:

I ran `sudo chmod 777 /Users/matt/.vagrant.d` and then ran `vagrant up` again.
## Error 8:

Upon the second run of `vagrant up` I received the following error:

```
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine_index.rb:321:in `initialize': Permission denied - /Users/matt/.vagrant.d/data/machine-index/index.lock (Errno::EACCES)
```
## Solution:

I ran `sudo vagrant up`
## Error 9:

Upon running `sudo vagrant up` I received the following error:

```
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 2375 is already in use
on the host machine.

To fix this, modify your current projects Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 2375, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding.
```
## Solution:

I opened `~/Sites/docking/Vagrantfile` in a text editor, and changed `2375` to another port (9885, which was just a random selection).  I tried to run `sudo vagrant up` and received the exact same error. I tried editing `~/Vagrantfile` and then running `sudo vagrant up` again.  I received the exact same error.  Finally, based on this stackoverflow post http://stackoverflow.com/a/25142933/1209832 I tried editing `~/.vagrant.d/boxes/yungsang-VAGRANTSLASH-boot2docker/1.4.1/virtualbox/Vagrantfile`.  Then I ran `sudo vagrant up` again, and it worked.
## Error 10:

I ran the following commands:

```
export DOCKER_HOST=tcp://localhost:9885
docker version
```

I received the following error:

```
FATA[0000] Get http://localhost:9885/v1.16/version: EOF. Are you trying to connect to a TLS-enabled daemon without TLS?
```
## Solution:
1. Ran `sudo brew install boot2docker`
2. Ran `boot2docker init`
3. Ran `boot2docker start`

Docker replied:

```
Waiting for VM and Docker daemon to start...
.......................ooooooooooooooooo
Started.
Writing /Users/matt/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/matt/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/matt/.boot2docker/certs/boot2docker-vm/key.pem

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.59.103:2376
    export DOCKER_CERT_PATH=/Users/matt/.boot2docker/certs/boot2docker-vm
    export DOCKER_TLS_VERIFY=1
```

So I gave the three `export` commands listed above.  And then FINALLY, I gave the command `docker version` and got the response:

```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.4
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

In truth, I don't really know what this means.  However, I did notice that I was now able to do this:

![docker](https://cloud.githubusercontent.com/assets/1197335/6417676/21be89ec-be7d-11e4-9b6e-20b1f9b94878.gif)

So I guess something happened?

**Comment by lmakarov** [comment]
Closing as outdated.
The setup process is pretty straightforward now and was tested on a fresh Yosemite 10.10.5.
