### ISSUE TITLE
Support for Docker 1.7.1 and Compose 1.3.3

### ISSUE THREAD

**Issue by yoanisgil** [blinkreaction/boot2docker-vagrant#30]
I was wondering if an upgrade to the latest stable version of docker/compose could be considered? I can put together a PR if this is something others my find useful.

I was also wondering if there should be a mechanism/option to easily do this without putting together a PR ever any of those components are updated

**Comment by lmakarov** [comment]
Hi @yoanisgil, updating docker client and docker-compose versions on a Mac host can easily be performed by changing version numbers inside the presetup-mac.sh script and re-running it.
See this PR: https://github.com/blinkreaction/boot2docker-vagrant/pull/33

As for the docker host side (the actual VM) - versions are currently built into the vagrant base box, which is maintained outside of this project:
https://github.com/lmakarov/boot2docker-vagrant-box/tree/docker-machine
The most recent base box version (1.7.1) already includes docker 1.7.1 and docker-compose 1.3.3.

1.7.1 is already used in the develop branch of this project (https://github.com/blinkreaction/boot2docker-vagrant/tree/develop). I plan to have a release out of the door in the next week or so.

**Comment by gaboesquivel** [comment]
one should always look for a develop branch I guess.. however perhaps a [contribute.md](https://github.com/blog/1184-contributing-guidelines) and contribute/collaborate section in readme are required

**Comment by lmakarov** [comment]
The current latest version [v1.0.0-rc2](https://github.com/blinkreaction/boot2docker-vagrant/releases/tag/v1.0.0-rc2) includes Docker 1.8.1 and Docker Compose 1.4.0.
