### ISSUE TITLE
Conflicts with default drude settings

### ISSUE THREAD

**Issue by frankcarey** [blinkreaction/boot2docker-vagrant#31]
### Issue

Installing drude causes this to be installed, but there is a conflict that causes the error:

>  $ dsh reset
>  ... 
> Creating devinciwebdrupal7_web_1...
> Cannot start container 5cb8370b6d828207980b85c8a5260feca72c1f1d0a9c76777b56e69d6397921c: Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
### Diagnosing

ssh into the boot2docker VM w/ vagrant

```
vagrant ssh 
```

check the listening ports

```
$ sudo netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 192.168.10.10:443       0.0.0.0:*               LISTEN      1495/docker-proxy
tcp        0      0 192.168.10.10:80        0.0.0.0:*               LISTEN      1503/docker-proxy
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      972/sshd
tcp        0      0 :::2375                 :::*                    LISTEN      1148/docker
tcp        0      0 :::3306                 :::*                    LISTEN      2900/docker-proxy
tcp        0      0 :::22                   :::*                    LISTEN      972/sshd
```

You should then be able to see what's listening on port 443, which in this case is the docker-proxy (aka vhost_proxy)
### Fix

Disable the vhost_proxy in the vagrant.yml file (usually up one level from the git repo). The Vagrantfile

``` Diff
# Use a reverse proxy to map host name to containers.
# This is an alternative to using dedicated IP addresses in the 'hosts' section above.
# Containers must define a "VIRTUAL_HOST" environment variable to be recognized and routed by the vhost-proxy.
- vhost_proxy: true
+ # vhost_proxy: true
```

Restart the VM

```
$ dsh restart
```

The restart should now be successful, but without the vhost_proxy setting, you'll need to set the hostname of your site manually.

```
sudo vim /etc/hosts
```

Add the line

```
192.168.10.10 hello-world.drude
```

You should now be able to view the site at http://hello-world.drude

**Comment by lmakarov** [comment]
Fixed in Drude [v1.0.0-rc1](https://github.com/blinkreaction/drude/releases/tag/v1.0.0-rc1)
