### ISSUE TITLE
NFS on Windows

### ISSUE THREAD

**Issue by angelcoding** [blinkreaction/boot2docker-vagrant#32]
Is it possible to allow the option of NFS on windows via the vagrant-winnfsd plugin?
https://github.com/winnfsd/vagrant-winnfsd

**Comment by lmakarov** [comment]
Hi @angelcoding I've been experimenting with NFS on Windows (including vagrant-winnfsd). It was very frustrating and never worked for me.
I'd recommend either using smb/smb2 or rsync options on Windows.

**Comment by angelcoding** [comment]
@lmakarov Funny. I've so far had the opposite experience - loads of problems with SMB and absolutely no problems with vagrant-winnfsd. What exactly didn't work? Was it too slow?

I've not yet benchmarked winnfsd and I read somewhere that in certain situations it can be slower than even vboxsf but I guess there might be potential to improve - plugin development seems quite active.

Seems a shame to completely dismiss it.

**Comment by lmakarov** [comment]
@angelcoding I do not remember the details other than I tried it hard and it did not work...
Do you think you can put together a PR and/or setup instructions?

**Comment by lmakarov** [comment]
@achekulaev could you please share your recent experience trying to get vagrant-winnfsd working?

**Comment by achekulaev** [comment]
vagrant-winnfsd doesn't work properly with assigned IP. At least not out-of-the box. I'm still struggling to get it to work

**Comment by lmakarov** [comment]
After many attempts to get this to work with different options I'm going to close this as won't fix.
