### ISSUE TITLE
NFS on Mac

### ISSUE THREAD

**Issue by FatherShawn** [blinkreaction/boot2docker-vagrant#59]
NFS was failing to mount in Mac OSX. Further investigation showed that the vagrant box could not be pinged from host and the host could not be pinged from within the vagrant machine.  Removing these directories/files and re-installing got me back up.

```
~/.vagrant
~/.vagrant.d
~/<project folder>/.vagrant
```

**Comment by FatherShawn** [comment]
This issue has spontaneously returned. And the steps above are now not restoring function.

**Comment by FatherShawn** [comment]
This time I deleted/uninstalled virtualbox in addition to the deletions above and then

```
brew cask install virtualbox
dsh self-update
dsh install prerequisites
dsh install boot2docker
```

And it's working again

**Comment by lmakarov** [comment]
@FatherShawn you don't have to install virtualbox via cask. The install prerequisites install script does this.

Glad this is working for you again.

One note - this repo does not use `dsh`. So anyone reading this - please follow the install and setup instructions in [README](https://github.com/blinkreaction/boot2docker-vagrant):
