### ISSUE TITLE
VirtualBox GuestAdditions property timesync-set-threshold doesn't adjust syncing box time to host

### ISSUE THREAD

**Issue by jmchuster** [blinkreaction/boot2docker-vagrant#61]
I'm trying to get the virtualbox to sync it's time with the host machine as described in these settings here: http://www.virtualbox.org/manual/ch09.html#changetimesync

modinfo vboxguest verifies that version 4.3.30 of VirtualBox Guest Additions is installed.

However, the following configuration in Vagrantfile seems to make no difference:
v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]

If you wait long enough (~30 minutes), the virtualbox will eventually sync to the host, so that at least verifies that the timesync service is running in some capacity.

**Comment by lmakarov** [comment]
@gingenhagen try updating to the latest VirtualBox 5.0+
We do not support/test on older versions.

**Comment by jmchuster** [comment]
@lmakarov I pulled the latest version of the box and the time sync seems to be fast now.  Many thanks on the awesome project.  My team is super-dependent on this box until Docker decides to fix https://github.com/boot2docker/boot2docker/issues/593

**Comment by lmakarov** [comment]
:+1: Glad it works for you :)
