### ISSUE TITLE
|| non valid parameter

### ISSUE THREAD

**Issue by xinity** [blinkreaction/boot2docker-vagrant#67]
since latest release , everytime i do a `vagrant up`

i have an error saying that `||` isn't a correct parameter.
this parameter is using in the vagrantfile to create the useraccount and the network share (smb windows).

how to fix ? any clue ?

**Comment by lmakarov** [comment]
@xinity I'm not getting this on Windows. Can you take a screenshot?

**Comment by xinity** [comment]
juste paste any command from the vagrantfile which uses '||' in your powershell

tested with windows 8 today, same error :(

**Comment by lmakarov** [comment]
@xinity, we only support Babun shell on Windows as noted in the README:

> Windows
> All automated scripts and instructions in this project assume using Babun shell and are not tested with other shells.

Do you run into such issues in Babun?

**Comment by xinity** [comment]
I can't trap them as powershell sub commands are wrapped, 
but it seems these command still fails even using babun.

**Comment by achekulaev** [comment]
@xinity I guess this will not move forward without screenshots or better screencast (you can use Jing or Monosnap free utlis for that)

**Comment by lmakarov** [comment]
Closing for the lack of feedback. Feel free to reopen.
