### ISSUE TITLE
Running dsh in vagrant box: tput: command not found

### ISSUE THREAD

**Issue by eelkeblok** [blinkreaction/boot2docker-vagrant#69]
I tried running the example from drude-d7-testing in boot2docker-vagrant. The first problem I encountered, which the instructions do not mention (I'll see if I can come up with a good pull request), is that there is an example docker-compose file that needs to be copied and renamed for things to work. 

However, I then run into this error:

```
$ dsh drush si -y
/usr/local/bin/dsh: line 945: tput: command not found
Error response from daemon: no such id: bash
```

Is this a missing dependency in the vagrant box? Or should I not be running dsh from within the box?

**Comment by lmakarov** [comment]
@eelkeblok this issue should be filed under https://github.com/blinkreaction/drude

To keep things short - I just pushed a release that will address both of the issues.
Please update dsh with `dsh self-update` and try again.

If you still run into problems - open an issue in https://github.com/blinkreaction/drude
