### ISSUE TITLE
Windows 10 shared folders with smb2

### ISSUE THREAD

**Issue by Entaro** [blinkreaction/boot2docker-vagrant#70]
Hello,

this vagrant box is really great, docker apps with shared folders works really fast on Mac, however i have problems with mounting shared folders on windows 10. I am doing everything according to documentation vagrant box starts properly i have access to docker in command line my docker-compose file starts containers correctly but when I try to enter inside container using docker exec shared folders are not present. Did you try it on windows 10, is there anything else that i need to make in order to make it work on windows 10?

**Comment by lmakarov** [comment]
Hi @Entaro, I'm testing this project primarily on a Windows 10 laptop, so it does work with Windows 10 for sure :)

Do you get any errors when the VM boots related to not being able to mount the SMB share?
Do you see the mounted folder in the VM itself? Do a `vagrant ssh` and check `mount`.

**Comment by Entaro** [comment]
@lmakarov i don't see any errors when VM boots.
I see mounted folders in the VM, but when I run containers with docker-compose up -d they are not present in container. However i tried to run docker-compose up -d from inside vagrant and it worked.

Now I am experiencing another issue after about 30 minutes of work something happens and docker is no longer available on windows host, when i try to run docker command i get this message "An error occurred trying to connect: Get http://192.168.10.10:2375/v1.21/containers/json: dial tcp 192.168.10.10:2375" But when i ssh into vagrant i can still display all docker processes with docker ps

**Comment by lmakarov** [comment]
@Entaro as for the mounts - you most likely have the volumes defined wrong in the `docker-compose.yml` file. It is best to define volume mappings using relative paths, e.g.:

```
  volumes:
    # Project root folder mapping
    - ".:/var/www"
```

As for the networking issue, see [this](https://github.com/blinkreaction/boot2docker-vagrant/blob/develop/docs/troubleshooting.md#various-networking-issues) and let me know whether that fixes the issue for you.

**Comment by Entaro** [comment]
I have my volumes defined using relative paths. This is my folder structure (screenshot is from mac but i have the same structure on windows)
![screen shot 2016-02-09 at 14 59 29](https://cloud.githubusercontent.com/assets/526482/12918153/d379f05a-cf3d-11e5-96e2-4d1474ec2f12.png)

and here is my compose configuration

``` html
mysql:
    build: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./dbstorage:/var/lib/mysql
      - ./db:/var/db

php:
    build: php-fpm
    links:
        - mysql:mysql
    ports:
        - 9003:9000
    volumes:
        - ./www:/var/www

symfony:
    build: php-fpm
    links:
        - mysql:mysql
    ports:
        - 9000:9000
    volumes:
        - ./www/symfony:/var/www/

nginx:
    build: nginx
    ports:
        - 80:80 # HOST:CONTAINER
    links:
        - php:php
        - symfony:symfony

    volumes:
        - ./www:/var/www
        - ./sites-enabled:/etc/nginx/sites-enabled
        - ./logs/nginx/:/var/log/nginx
```

In terms of networking issue i can enter to VM console.

**Comment by lmakarov** [comment]
@Entaro is this still a relevant issue for you?

**Comment by Entaro** [comment]
I stopped experimenting with it on windows, now I am mostly working on Mac and everything works fine there.
