### ISSUE TITLE
Mac: Boot2docker stuck on "Mounting NFS shared folders" step

### ISSUE THREAD

**Issue by haixiang** [blinkreaction/boot2docker-vagrant#9]
If OSX firewall is turned on and "Block all incoming connections" setting is checked http://monosnap.com/image/N96ywNZf4FDLf8i2Y2xvp0slw8Y8w8.png - folders cannot be mounted and the script is stuck on the "Mounting NFS shared folders" step.
Disabling this setting resolves the issue.

**Comment by lmakarov** [comment]
I would also recommend disabling "Stealth mode" if possible. This will substantially speed up the NFS mount process.

http://take.ms/X7fvo

**Comment by kyleskrinak** [comment]
I'm wondering if [lmakarov's](https://github.com/lmakarov) "disable stealth mode" OSX instruction is important enough to put one your configuration instructions. Making this change has reduced my mount time from 120 seconds-ish to 8 seconds. Also, FWIW, a recent `brew update` broke my NFS mounting process, somehow, causing it to halt on the mount step. Reloading the script in the automatic installation section addressed this.
